test:
#  hostport: httpbin.org:80
#  hostport: localhost:5000
#  uri: http://${test.hostport}
#  uri: lb://httpbin

server:
  port: 8090


eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

spring:
  application:
    name: spring-cloud-gateway-sample
  jmx:
    enabled: false
  cloud:
    # 固定前缀
    gateway:
      default-filters:
      - PrefixPath=/test
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      # 路由列表，可定义多个路由
      routes:
      # =====================================
      # to run server
      # $ wscat --listen 9000
      # to run client
      # $ wscat --connect ws://localhost:8080/echo
        # 声明一个 id 为 websocket_test 的路由
      - id: websocket_test
        # 定义了路由的目的地 url，即请求转发的地址
        uri: ws://localhost:9000
        order: 9000
        # 定一个一个 Predicate，path 为 /echo 才能够匹配，由 PathRoutePredicateFactory 来生产
        predicates:
        - Path=/echo
        # 定义 filters，即路由转发前后处理的过滤器
        filters:
        # 定义一个 Filter，所有的请求转发至下游服务时会添加请求头 X-Request-Foo:Bar，由 AddRequestHeaderGatewayFilterFactory 来生产
        - AddRequestHeader=X-Request-Foo, Bar
      # =====================================
#      - id: default_path_to_httpbin
#        uri: ${test.uri}
#        order: 10000
#        predicates:
#        - Path=/**
      # =====================================
      - id: baidu_test
        uri: https://www.cnblogs.com/listjiang/p/15351351.html
        order: 10010
        predicates:
        - Path=/baidu
      # 初始化 GatewayDiscoveryClientAutoConfiguration
      enabled: true
      # 初始化 DiscoveryClientRouteDefinitionLocator
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management.endpoints.web.exposure.include: '*'
